### ISSUE TITLE
failed to mount local volume

### ISSUE THREAD

**Issue by officestarmb** [damalis/full-stack-apache2-magento-for-everyone-with-docker-compose#1]
⠋ Container database  Creating                                                                                                                                                                             0.1s
Error response from daemon: failed to mount local volume: mount /magento/full-stack-apache2-magento-for-everyone-with-docker-compose/phpmyadmin/sql:/var/lib/docker/volumes/phpmyadmin-sql/_data, flags: 0x1000: no such file or directory

**Comment by damalis** [comment]
I tried and not get any problem.

OS: **Ubuntu 20.04 LTS 1 GB RAM, 1 vCPU, 40 GB SSD and swap: 2G**

I setted vm.max_map_count value from [here](https://www.elastic.co/guide/en/elasticsearch/reference/8.5/docker.html#_set_vm_max_map_count_to_at_least_262144)
